[env]
# Target newer Windows version in MinGW. Required to build mimalloc.
TARGET_CFLAGS = "-D_WIN32_WINNT=0x601"

[target.thumbv8m.main-none-eabihf]
# Pass some extra options to rustc, some of which get passed on to the linker.
#
# * linker argument --nmagic turns off page alignment of sections (which saves
#   flash space)
# * linker argument -Tlink.x tells the linker to use link.x as a linker script.
#   This is usually provided by the cortex-m-rt crate, and by default the
#   version in that crate will include a file called `memory.x` which describes
#   the particular memory layout for your specific chip.
# * linker argument -Tdefmt.x also tells the linker to use `defmt.x` as a
#   secondary linker script. This is required to make defmt_rtt work.
rustflags = [
    "-C", "linker=flip-link",
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "target-cpu=cortex-m33",
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-C", "linker=clang",
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "link-args=-Wl,--icf=all",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "linker=clang",
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "link-args=-Wl,--icf=all",
]
